### ISSUE TITLE
G3の音がG＃3で再生される

### ISSUE THREAD

**Issue by f-t-ikt** [respyb/happy-birthday-2023#7]
多分ここ 195.998 です.
cf. https://tomari.org/main/java/oto.html
https://github.com/respyb/happy-birthday-2023/blob/0bec7d3ab8c4542195246245930f1491455ce1ed/src/notes.tsx#L52

**Comment by respyb** [comment]
ありがとうございます！
ホントですね...早速修正PR作らせていただきました。
ご指摘感謝です！
